### ISSUE TITLE
Which versions of HighCharts are supported?

### ISSUE THREAD

**Issue by danmattsson** [downdrown/VaadinHighChartsAPI#11]
As the itle says, which versions are supported? Specifically, would HighCharts version 2 work, as that is what we're using today?

**Comment by downdrown** [comment]
I don't really get the topic of your question, but if you mean which highcharts.js script is included, you could see that [here](https://github.com/downdrown/VaadinHighChartsAPI/blob/master/src/main/resources/at/downdrown/vaadinaddons/highchartsapi/highcharts.js).

Currently **v4.1.7** is packaged.

If this did it for you please let me know!

**Comment by danmattsson** [comment]
Sorry, should've been more specific (and quicker to respond). I assumed that I would download HighCharts separately from the API, I understand from your comment that that is not the case.

Thanks!
