### ISSUE TITLE
Ability to use served/CDN versions of HighCharts scripts

### ISSUE THREAD

**Issue by danmattsson** [downdrown/VaadinHighChartsAPI#12]
Is it possible to use the CDN versions of the scripts or do we need to download (and serve ourselves) the JS code?

**Comment by downdrown** [comment]
Simply - **No, it's not**.

I tried to implement it as dynamically like you suggested, but there were many problems loading the js from an SSL context, as you can see at bug #9.
So it was basically easier to pack the .js as static content.

Maybe someday I will implement it like this again, but I cannot promise by now.
At the moment I implemented many other chart types and added a type-safe API for the chart's data, but I got a lot of work and often have no time for my addon!

But feel free to implement this feature if you like to!

**Comment by danmattsson** [comment]
Thanks, I'll have a look to see if Merzod suggestion referenced below solves the HTTP/HTTPS issue, I believe it should.

https://github.com/downdrown/VaadinHighChartsAPI/issues/9#issuecomment-124497022
