### ISSUE TITLE
PlotOptions Serialization

### ISSUE THREAD

**Issue by DavidBrehm2** [downdrown/VaadinHighChartsAPI#14]
In HighChartsPlotOptionsImpl.java:260

```
builder.append(", step: " + steps.name());
```

quotation marks are missing - should be:

```
builder.append(", step: '" + steps.name() + "'");
```

Can confirm that the Addon works with this change and the  Vaadin 7.5.5 js issue #13 change

**Comment by downdrown** [comment]
Thank you very much! I will correct this bug tomorrow and re-publish this version for you all!

**Comment by downdrown** [comment]
Fixed right now.
