### ISSUE TITLE
HighChartsPlotOptionsImpl#step needs to remove parentheses in #getHightChartValue

### ISSUE THREAD

**Issue by smigfu** [downdrown/VaadinHighChartsAPI#15]
HighChartsPlotOptionsImpl line 260 is

```
    builder.append(", step: '" + steps.name() + "'");
```

but should be

```
    builder.append(", step: " + steps.name().toLowerCase());
```

Currently it always shows (Line-) charts with steps, even though it default to FALSE in the implementation,

**Comment by smigfu** [comment]
Oddly it states different in the HightChars documentation though: http://api.highcharts.com/highcharts#plotOptions.line.step

**Comment by downdrown** [comment]
Thank you for the hint! I will fix this as soon as possible!

**Comment by DavidBrehm2** [comment]
HighCharts documentation seems to be wrong:
http://jsfiddle.net/rgugbfc2/1/
So 'left' 'right' and 'center' should be a String - false should be Boolean.

Proposed change: HighChartsPlotOptionsImpl:260

```
if (steps.equals(Steps.FALSE)) {
    builder.append(", step: " + Boolean.FALSE);
} else {
    builder.append(", step: '" + steps.name().toLowerCase() + "'");
}
```

**Comment by downdrown** [comment]
Thank you for the hint, just implemented this.
