### ISSUE TITLE
AreaChartSeries should return ChartType.AREA but is ChartType.LINE

### ISSUE THREAD

**Issue by smigfu** [downdrown/VaadinHighChartsAPI#2]

**Comment by downdrown** [comment]
Thank you for that information! I will fix that in my next release!

**Comment by smigfu** [comment]
Just saw the same issue in the AreaChartPlotOptions too

**Comment by downdrown** [comment]
Okay thank you! Seems like a typical Copy & Paste bug to me. I will fix that.

**Comment by downdrown** [comment]
Solved.
