### ISSUE TITLE
Failed to find widgetset

### ISSUE THREAD

**Issue by kokkachris** [downdrown/VaadinHighChartsAPI#4]
Hi,

I am using maven to build my project and I have added the dependency and tried to compile the widgetset, but I keep on getting this error. I have spent more than a day trying to fix this. My Vaadin version is 7.4. I have followed all the instructions on these links: 
![image](https://cloud.githubusercontent.com/assets/9993482/7489601/3daed79e-f3e1-11e4-99da-89671374706d.png)

Let me know if I can provide any more information.

The error is as follows: 

[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:7.4.3:compile (default) on project analyzeEM: GWT Module at.downdrown.vaadinaddons.highchartsapi.WidgetSet not found in project sources or resources. -

> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.vaadin:vaadin-maven-plugin:7.4.3:compile (default) on project analyzeEM: GWT Module at.downdrown.vaadinaddons.highchartsapi.Widget
> Set not found in project sources or resources.
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
>         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
>         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
>         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
>         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
>         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
>         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
>         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
>         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
>         at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:483)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Caused by: org.apache.maven.plugin.MojoExecutionException: GWT Module at.downdrown.vaadinaddons.highchartsapi.WidgetSet not found in project sources or resources.
>         at org.codehaus.mojo.gwt.shell.CompileMojo.compilationRequired(CompileMojo.java:497)
>         at org.codehaus.mojo.gwt.shell.CompileMojo.compile(CompileMojo.java:357)
>         at org.codehaus.mojo.gwt.shell.CompileMojo.doExecute(CompileMojo.java:281)
>         at org.codehaus.mojo.gwt.shell.AbstractGwtShellMojo.execute(AbstractGwtShellMojo.java:172)
>         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
>         ... 19 more
> Caused by: org.codehaus.mojo.gwt.utils.GwtModuleReaderException: GWT Module at.downdrown.vaadinaddons.highchartsapi.WidgetSet not found in project sources or resources.
>         at org.codehaus.mojo.gwt.AbstractGwtModuleMojo.readModule(AbstractGwtModuleMojo.java:214)
>         at org.codehaus.mojo.gwt.GwtModule.getLocalInherits(GwtModule.java:189)
>         at org.codehaus.mojo.gwt.GwtModule.getInherits(GwtModule.java:149)
>         at org.codehaus.mojo.gwt.GwtModule.getEntryPoints(GwtModule.java:114)
>         at org.codehaus.mojo.gwt.shell.CompileMojo.compilationRequired(CompileMojo.java:410)
>         ... 24 more

**Comment by downdrown** [comment]
Here is my Widgetset from another project. This works fine for me and I never had a problem to compile the widgetset. Did you inherit it in your own widgetset?

```
<module>
    <inherits name="com.vaadin.DefaultWidgetSet"/>
    <inherits name="org.vaadin.jouni.dom.DomWidgetset"/>
    <inherits name="org.vaadin.jouni.animator.AnimatorWidgetset"/>
    <inherits name="at.downdrown.vaadinaddons.highchartsapi.WidgetSet" />
</module>
```

**Comment by downdrown** [comment]
Solved.

**Comment by nicoo222** [comment]
Fuck it all
