### ISSUE TITLE
How set Axis x and Y

### ISSUE THREAD

**Issue by jonapin006** [downdrown/VaadinHighChartsAPI#6]
How I setup the Axis to ChartType.COLUMN and ChartConfiguration, thanks

**Comment by downdrown** [comment]
Could you please add an example what exactly you mean?

**Comment by jonapin006** [comment]
This is the example
![use](https://cloud.githubusercontent.com/assets/12478371/7801734/29497f4e-02ef-11e5-8a69-2f5db5eb1bd1.png)

**Comment by jonapin006** [comment]
Hi, any idea?

**Comment by downdrown** [comment]
Sorry I haven't found any time to reply ... I still do not really know what you mean but I will try to tinker a example and hope I can help you! I will post it here in the comments as soon as I have time for it!

**Comment by downdrown** [comment]
![screenshot 2015-05-28 10 25 01](https://cloud.githubusercontent.com/assets/3913600/7855698/02e1a390-0524-11e5-83a1-78827e7082a1.png)

If you meant only to set the chart's categories (like on the image) you could do it like this:

``` java
ChartConfiguration columnConfiguration = new ChartConfiguration();
columnConfiguration.setTitle("TestColumn");
columnConfiguration.setChartType(ChartType.COLUMN);
columnConfiguration.setBackgroundColor(Colors.WHITE);

List<String> categories = new ArrayList<String>();
categories.add("Some");
categories.add("Category");
categories.add("Text");

columnConfiguration.getxAxis().setCategories(categories);
```

Best Regards,
Manfred

**Comment by jonapin006** [comment]
Great, it works!!

Thank you
