### ISSUE TITLE
styles.css not found

### ISSUE THREAD

**Issue by joshua-schnabel** [downdrown/VaadinHighChartsAPI#7]
I get this information when I use your plugin: 

INFO: Requested resource [/VAADIN/widgetsets/XXX.XXX/highchartsapi/styles.css] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.

**Comment by downdrown** [comment]
I will remove the widgetset completly, since I don't have any custom widget and it only delivers problems!

**Comment by downdrown** [comment]
Fixed. (Removed Widgetset from AddOn)
