### ISSUE TITLE
Blocked loading mixed active content "http://code.jquery.com/jquery-2.1.3.min.js"

### ISSUE THREAD

**Issue by manu-l** [downdrown/VaadinHighChartsAPI#9]
Hello,

First thanks for this extension.
I was trying to make tests but I get an error because in the class HighChart, there is 2 references to external JS libraries : 
@JavaScript({"http://code.jquery.com/jquery-2.1.3.min.js", "http://code.highcharts.com/highcharts.js", "highcharts-connector.js"})

As my web site is in httpS the call to these libraries throws the 2 following exceptions 
- Blocked loading mixed active content "http://code.jquery.com/jquery-2.1.3.min.js"[
- Blocked loading mixed active content "http://code.highcharts.com/highcharts.js"

It's because the httpS web site is trying to access to unsecure content, ie http content (see https://developer.mozilla.org/fr/docs/S%C3%A9curit%C3%A9/MixedContent). I could also be an issue if somebody wants to use your library from an intranet where there is no internet access.
An easy way to solve that would be to host these 2 files inside the jar like you do for the JS file "highcharts-connector.js". Perhaps you could propose 2 versions, the actual one which requires an internet access and another "offline" version.

Thank for your work!

EDIT : Users can also enable the blocked content but it is a technical operation (it works in firefox I didn't test the other browsers).

**Comment by downdrown** [comment]
Thank you for the hint! Of course this was a conscious decision of mine. I wanted to keep the addon flexible and add as minimum static content as possible, but i will think of the idea with two versions!

Best regards!

**Comment by merzod** [comment]
Hi Manfred.
Thanks for the great extension!
About this issue, but from other angle. It would be cool if you update @JavaScript annotation in HighChart.java from HTTP links to HTTPS. Because if your Web Application works over HTTPS currently Chrome doesn't show Chart at all, and places small icon in address line

**Comment by downdrown** [comment]
Thank you! I'm happy you guys like my AddOn!

I solved the issue now and made the JavaScript files static. It was an idea to keep the AddOn mostly Up-To-Date with new Libraries but there are too many troubles with that.
So in my next release this won't be a problem any more!

Cheers
